use Copernic_verifone

select *
from Copernic_verifone.dbo.sales
where  PAYMENTDATE > convert(date,getdate()-1)
order by PAYMENTDATE desc



select *
from salesInformation
where  PAYMENTDATE > convert(date,getdate()-1)
    and ORDERNO =  183000
order by PAYMENTDATE desc


SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = N'salesProducts'


--***insert sales missing from salesinformation table
--insert into salesInformation (MESSAGE_ID,REFNO,ORDERNO,GIFT_ORDER,SALEDATE,PAYMENTDATE,REFNOEXT,SHOPPER_REFERENCE_NUMBER,ORIGINAL_REFNOEXT,ORDERSTATUS,PAYMETHOD_CODE,CARD_TYPE,CARD_LAST_DIGITS,CARD_EXPIRATION_DATE,CURRENCY,LANGUAGE,ORDERFLOW,FX_RATE,FX_MARKUP,PAYABLE_AMOUNT,PAYOUT_CURRENCY,SHIPPING_TRACKING_NO,SHIPPING_COMMENTS,SHIPPING_TRACKING_URL,SHIPPING_METHOD_NAME,SHIPPING_STATUS,CHARGEBACK_RESOLUTION,CHARGEBACK_REASON_CODE,TEST_ORDER,GATEWAY_RESPONSE,IPN_ORDER_ORIGIN,REFUND_REASON,FRAUD_STATUS,MESSAGE_TYPE,VENDOR_CODE,PROPOSAL_ID,AVANGATE_CUSTOMER_REFERENCE,EXTERNAL_CUSTOMER_REFERENCE,REFUND_TYPE,IPN_CUSTOM_TEXT,IPN_CUSTOM_VALUE,IPN_DATE,COMPLETE_DATE,CUSTOM_PRICE,IPN_REFERRER,TAX_OFFICE,TIMEZONE_OFFSET)
select MESSAGE_ID, REFNO, ORDERNO, GIFT_ORDER, SALEDATE, PAYMENTDATE, REFNOEXT, SHOPPER_REFERENCE_NUMBER, ORIGINAL_REFNOEXT, ORDERSTATUS, PAYMETHOD_CODE, CARD_TYPE, CARD_LAST_DIGITS, CARD_EXPIRATION_DATE, CURRENCY, LANGUAGE, ORDERFLOW, FX_RATE, FX_MARKUP, PAYABLE_AMOUNT, PAYOUT_CURRENCY, SHIPPING_TRACKING_NO, SHIPPING_COMMENTS, SHIPPING_TRACKING_URL, SHIPPING_METHOD_NAME, SHIPPING_STATUS, CHARGEBACK_RESOLUTION, CHARGEBACK_REASON_CODE, TEST_ORDER, GATEWAY_RESPONSE, IPN_ORDER_ORIGIN, REFUND_REASON, FRAUD_STATUS, MESSAGE_TYPE, VENDOR_CODE, PROPOSAL_ID, AVANGATE_CUSTOMER_REFERENCE, EXTERNAL_CUSTOMER_REFERENCE, REFUND_TYPE, IPN_CUSTOM_TEXT, IPN_CUSTOM_VALUE, IPN_DATE, COMPLETE_DATE, CUSTOM_PRICE, IPN_REFERRER, TAX_OFFICE, TIMEZONE_OFFSET
from sales
where refno = ''


--***insert sales products missing
--insert into salesProducts (ORDERNO,REFNO,IPN_PID,IPN_PNAME,IPN_PCODE,IPN_EXTERNAL_REFERENCE,IPN_INFO,IPN_QTY,IPN_PRICE,IPN_VAT,IPN_VAT_RATE,IPN_VER,IPN_DISCOUNT,IPN_PROMOTION_CATEGORY,IPN_PROMONAME,IPN_PROMOCODE,IPN_PROMO_IDCODE,IPN_ORDER_COSTS,IPN_SKU,IPN_PARTNER_CODE,IPN_PGROUP,IPN_PGROUP_NAME,IPN_PCOMMISSION,IPN_LICENSE_PROD,IPN_LICENSE_TYPE,IPN_LICENSE_REF,IPN_LICENSE_EXP,IPN_LICENSE_START,IPN_LICENSE_LIFETIME,IPN_LICENSE_ADDITIONAL_INFO,IPN_DELIVEREDCODES,IPN_DOWNLOAD_LINK,IPN_TOTAL,IPN_TOTALGENERAL,IPN_SHIPPING,IPN_SHIPPING_TAX,IPN_PARTNER_MARGIN_PERCENT,IPN_PARTNER_MARGIN,IPN_EXTRA_MARGIN,IPN_EXTRA_DISCOUNT,IPN_COUPON_DISCOUNT,IPN_ORIGINAL_LINK_SOURCE,IPN_RESELLER_ID,IPN_RESELLER_NAME,IPN_RESELLER_URL,IPN_RESELLER_COMMISSION,IPN_COMMISSION,IPN_PRODUCT_OPTIONS_1234_OPERATOR,IPN_PRODUCT_OPTIONS_1234_OPTIONAL_VALUE,IPN_PRODUCT_OPTIONS_1234_PRICE,IPN_PRODUCT_OPTIONS_1234_TEXT,IPN_PRODUCT_OPTIONS_1234_USAGE,IPN_PRODUCT_OPTIONS_1234_VALUE,IPN_BUNDLE_DETAILS_1234_PID,IPN_BUNDLE_DETAILS_1234_PNAME,IPN_BUNDLE_DETAILS_1234_PCODE,IPN_BUNDLE_DETAILS_1234_QTY,IPN_BUNDLE_DETAILS_1234_SKU,IPN_BUNDLE_DETAILS_1234_PGROUP,IPN_BUNDLE_DETAILS_1234_PGROUP_NAME,IPN_BUNDLE_DELIVEREDCODES_1234)
select ORDERNO, REFNO, IPN_PID, IPN_PNAME, IPN_PCODE, IPN_EXTERNAL_REFERENCE, IPN_INFO, IPN_QTY, IPN_PRICE, IPN_VAT, IPN_VAT_RATE, IPN_VER, IPN_DISCOUNT, IPN_PROMOTION_CATEGORY, IPN_PROMONAME, IPN_PROMOCODE, IPN_PROMO_IDCODE, IPN_ORDER_COSTS, IPN_SKU, IPN_PARTNER_CODE, IPN_PGROUP, IPN_PGROUP_NAME, IPN_PCOMMISSION, IPN_LICENSE_PROD, IPN_LICENSE_TYPE, IPN_LICENSE_REF, IPN_LICENSE_EXP, IPN_LICENSE_START, IPN_LICENSE_LIFETIME, IPN_LICENSE_ADDITIONAL_INFO, IPN_DELIVEREDCODES, IPN_DOWNLOAD_LINK, IPN_TOTAL, IPN_TOTALGENERAL, IPN_SHIPPING, IPN_SHIPPING_TAX, IPN_PARTNER_MARGIN_PERCENT, IPN_PARTNER_MARGIN, IPN_EXTRA_MARGIN, IPN_EXTRA_DISCOUNT, IPN_COUPON_DISCOUNT, IPN_ORIGINAL_LINK_SOURCE, IPN_RESELLER_ID, IPN_RESELLER_NAME, IPN_RESELLER_URL, IPN_RESELLER_COMMISSION, IPN_COMMISSION, IPN_PRODUCT_OPTIONS_1234_OPERATOR, IPN_PRODUCT_OPTIONS_1234_OPTIONAL_VALUE, IPN_PRODUCT_OPTIONS_1234_PRICE, IPN_PRODUCT_OPTIONS_1234_TEXT, IPN_PRODUCT_OPTIONS_1234_USAGE, IPN_PRODUCT_OPTIONS_1234_VALUE, IPN_BUNDLE_DETAILS_1234_PID, IPN_BUNDLE_DETAILS_1234_PNAME, IPN_BUNDLE_DETAILS_1234_PCODE, IPN_BUNDLE_DETAILS_1234_QTY, IPN_BUNDLE_DETAILS_1234_SKU, IPN_BUNDLE_DETAILS_1234_PGROUP, IPN_BUNDLE_DETAILS_1234_PGROUP_NAME, IPN_BUNDLE_DELIVEREDCODES_1234
from sales
where refno = ''






select
    CONVERT(DATE, s.PAYMENTDATE) AS PAYMENTDATE,
    Format(SUM(sp.IPN_TOTAL * s.FX_RATE), 'N3') AS totalSale
from Copernic_verifone.dbo.salesProducts sp
    join Copernic_verifone.dbo.salesInformation  s on s.REFNO = sp.REFNO
where s.ORDERSTATUS = 'COMPLETE'
GROUP BY CONVERT(DATE, s.PAYMENTDATE)
ORDER BY PAYMENTDATE DESC;


--total sale per day
SELECT
    CONVERT(DATE, PAYMENTDATE) AS PAYMENTDATE,
    Format(SUM(IPN_TOTAL * FX_RATE), 'N3') AS totalSale
FROM Copernic_verifone.dbo.sales
where ORDERSTATUS = 'COMPLETE'
GROUP BY CONVERT(DATE, PAYMENTDATE)
ORDER BY PAYMENTDATE DESC;



--Total sales for the month
SELECT
    FORMAT(SUM(IPN_TOTAL * FX_RATE), 'N2') AS totalSaleForApril
FROM Copernic_verifone.dbo.sales
WHERE MONTH(PAYMENTDATE) = 5
    and ORDERSTATUS = 'COMPLETE'
    AND YEAR(PAYMENTDATE) = YEAR(GETDATE());



select id, FIRSTNAME, LASTNAME, ADDRESS1, city, [STATE], ZIPCODE, country, COUNTRYCODE
from Copernic_verifone.dbo.CustomerInformation
--where id =15
order by creationdate desc


select *
from Copernic_verifone.dbo.WebHooksLogs
where   CreationDate > convert(date,getdate()-5)
    and Severity <> 0


