-- QUERY TO GET THE LIST OF PRODUCTS WITH AT LEAST ONE SPEC REPEATED (TWICE OR MORE)
SELECT	* 
FROM	Products PP
WHERE
	EXISTS (
		SELECT	TOP(1) 1
		FROM	SpecsProd SP
		WHERE	SP.ProductId = PP.Id_Product
		GROUP BY  SP.ProductID, SP.SpecID
		HAVING COUNT(SP.SpecID) > 1
	)
