DECLARE @TargetId AS INT = 1680 

UPDATE Cr
SET
	Cr.Newsletter = C.Newsletter,
	Cr.Aboutus = C.Aboutus,
	Cr.TermsPolicy = C.TermsPolicy,
	Cr.merchantstore = C.merchantstore,
	Cr.contactform = C.contactform,
	Cr.askexpert = C.askexpert,
	Cr.quoterequest = C.quoterequest,
	Cr.sShowImage = C.sShowImage,
	Cr.sShowLink = C.sShowLink,
	Cr.sShowText = C.sShowText,
	Cr.relatedProducts = C.relatedProducts,
	Cr.SeoText = C.SeoText,
	Cr.storedetailsformat = C.storedetailsformat,
	Cr.sShowImageMinLimit = C.sShowImageMinLimit,
	Cr.sShowImageMaxLimit = C.sShowImageMaxLimit,
	Cr.updateProduction = C.updateProduction,
	Cr.newslettertype = C.newslettertype,
	Cr.LiquidationManagement = C.LiquidationManagement,
	Cr.HomeAds = C.HomeAds,
	Cr.HomeAdsLink = C.HomeAdsLink,
	Cr.orders = C.orders,
	Cr.warranties = C.warranties,
	Cr.requestemailmessage = C.requestemailmessage,
	Cr.requestsubmitmessage = C.requestsubmitmessage,
	Cr.showManufacturerPrice = C.showManufacturerPrice,
	Cr.MaxProductCount = C.MaxProductCount,
	Cr.serverEnvironment = C.serverEnvironment,
	Cr.mcontentpages = C.mcontentpages,
	Cr.HotDeals = C.HotDeals,
	Cr.featuredItemTabs = C.featuredItemTabs,
	Cr.websiteScripts = C.websiteScripts,
	Cr.productLock = C.productLock,
	Cr.uploadVideoReview = C.uploadVideoReview,
	Cr.RTOConsole = C.RTOConsole,
	Cr.NmgRebates = C.NmgRebates,
	Cr.altAdText = C.altAdText,
	Cr.NmgRebateActive = C.NmgRebateActive,
	Cr.NmgRebateDefaultShow = C.NmgRebateDefaultShow,
	Cr.RebateMultiFiles = C.RebateMultiFiles,
	Cr.AdsTimers = C.AdsTimers,
	Cr.adsVideoLink = C.adsVideoLink,
	Cr.viewRebateDetail = C.viewRebateDetail,
	Cr.brandLandingPages = C.brandLandingPages,
	Cr.openTransitionPages = C.openTransitionPages,
	Cr.pageHeaderCode = C.pageHeaderCode,
	Cr.transitionPages = C.transitionPages,
	Cr.taxManagement = C.taxManagement,
	Cr.discountsTool = C.discountsTool,
	Cr.brandLandingPageCustomTemplate = C.brandLandingPageCustomTemplate,
	Cr.UseBrandHidden = C.UseBrandHidden,
	Cr.hasProductTags = C.hasProductTags,
	Cr.hasDingAndDent = C.hasDingAndDent,
	Cr.hasURLEmbedVideo = C.hasURLEmbedVideo,
	Cr.hasLoginPasswordPage = C.hasLoginPasswordPage,
	Cr.hasFlyerImagesManagement = C.hasFlyerImagesManagement,
	Cr.transitionPageCustomTemplate = C.transitionPageCustomTemplate,
	Cr.itemReviews = C.itemReviews,
	Cr.feedManagement = C.feedManagement,
	Cr.hasLexicons = C.hasLexicons,
	Cr.hasBlog = C.hasBlog,
	Cr.slideShowPositionChange = C.slideShowPositionChange,
	Cr.hasOPR = C.hasOPR,
	Cr.hasDefaultPushCents = C.hasDefaultPushCents,
	Cr.defaultPushCents = C.defaultPushCents,
	Cr.seoManagement = C.seoManagement,
	Cr.hasURLMapping = C.hasURLMapping,
	Cr.HoursToKeepClaimedQuotesInStoreInbox = C.HoursToKeepClaimedQuotesInStoreInbox,
	Cr.autoPushEmail = C.autoPushEmail,
	Cr.useDescriptiveTitle = C.useDescriptiveTitle,
	Cr.htmlAdText = C.htmlAdText,
	Cr.responsiveAdParamKeys = C.responsiveAdParamKeys
FROM MerchantCMS Cr
	JOIN MerchantCMS C ON C.Merchant_Id = 1210 -- MEGA DESIGN DEMO
WHERE (
	Cr.Merchant_Id = @TargetId
)
AND 
(
	1 = 0
	OR Cr.Newsletter != C.Newsletter
	OR Cr.Aboutus != C.Aboutus
	OR Cr.TermsPolicy != C.TermsPolicy
	OR Cr.merchantstore != C.merchantstore
	OR Cr.contactform != C.contactform
	OR Cr.askexpert != C.askexpert
	OR Cr.quoterequest != C.quoterequest
	OR Cr.sShowImage != C.sShowImage
	OR Cr.sShowLink != C.sShowLink
	OR Cr.sShowText != C.sShowText
	OR Cr.relatedProducts != C.relatedProducts
	OR Cr.SeoText != C.SeoText
	OR Cr.storedetailsformat != C.storedetailsformat
	OR Cr.sShowImageMinLimit != C.sShowImageMinLimit
	OR Cr.sShowImageMaxLimit != C.sShowImageMaxLimit
	OR Cr.updateProduction != C.updateProduction
	OR Cr.newslettertype != C.newslettertype
	OR Cr.LiquidationManagement != C.LiquidationManagement
	OR Cr.HomeAds != C.HomeAds
	OR Cr.HomeAdsLink != C.HomeAdsLink
	OR Cr.orders != C.orders
	OR Cr.warranties != C.warranties
	OR Cr.requestemailmessage != C.requestemailmessage
	OR Cr.requestsubmitmessage != C.requestsubmitmessage
	OR Cr.showManufacturerPrice != C.showManufacturerPrice
	OR Cr.MaxProductCount != C.MaxProductCount
	OR Cr.serverEnvironment != C.serverEnvironment
	OR Cr.mcontentpages != C.mcontentpages
	OR Cr.HotDeals != C.HotDeals
	OR Cr.featuredItemTabs != C.featuredItemTabs
	OR Cr.websiteScripts != C.websiteScripts
	OR Cr.productLock != C.productLock
	OR Cr.uploadVideoReview != C.uploadVideoReview
	OR Cr.RTOConsole != C.RTOConsole
	OR Cr.NmgRebates != C.NmgRebates
	OR Cr.altAdText != C.altAdText
	OR Cr.NmgRebateActive != C.NmgRebateActive
	OR Cr.NmgRebateDefaultShow != C.NmgRebateDefaultShow
	OR Cr.RebateMultiFiles != C.RebateMultiFiles
	OR Cr.AdsTimers != C.AdsTimers
	OR Cr.adsVideoLink != C.adsVideoLink
	OR Cr.viewRebateDetail != C.viewRebateDetail
	OR Cr.brandLandingPages != C.brandLandingPages
	OR Cr.openTransitionPages != C.openTransitionPages
	OR Cr.pageHeaderCode != C.pageHeaderCode
	OR Cr.transitionPages != C.transitionPages
	OR Cr.taxManagement != C.taxManagement
	OR Cr.discountsTool != C.discountsTool
	OR Cr.brandLandingPageCustomTemplate != C.brandLandingPageCustomTemplate
	OR Cr.UseBrandHidden != C.UseBrandHidden
	OR Cr.hasProductTags != C.hasProductTags
	OR Cr.hasDingAndDent != C.hasDingAndDent
	OR Cr.hasURLEmbedVideo != C.hasURLEmbedVideo
	OR Cr.hasLoginPasswordPage != C.hasLoginPasswordPage
	OR Cr.hasFlyerImagesManagement != C.hasFlyerImagesManagement
	OR Cr.transitionPageCustomTemplate != C.transitionPageCustomTemplate
	OR Cr.itemReviews != C.itemReviews
	OR Cr.feedManagement != C.feedManagement
	OR Cr.hasLexicons != C.hasLexicons
	OR Cr.hasBlog != C.hasBlog
	OR Cr.slideShowPositionChange != C.slideShowPositionChange
	OR Cr.hasOPR != C.hasOPR
	OR Cr.hasDefaultPushCents != C.hasDefaultPushCents
	OR Cr.defaultPushCents != C.defaultPushCents
	OR Cr.seoManagement != C.seoManagement
	OR Cr.hasURLMapping != C.hasURLMapping
	OR Cr.HoursToKeepClaimedQuotesInStoreInbox != C.HoursToKeepClaimedQuotesInStoreInbox
	OR Cr.autoPushEmail != C.autoPushEmail
	OR Cr.useDescriptiveTitle != C.useDescriptiveTitle
	OR Cr.htmlAdText != C.htmlAdText
	OR Cr.responsiveAdParamKeys != C.responsiveAdParamKeys
)