insert into MerchantSharedWebsitePages (merchantID, SharedWebsitePageId, AlwaysRecalculate)
values (1507, 1, 1)
insert into MerchantSharedWebsitePages (merchantID, SharedWebsitePageId, AlwaysRecalculate)
values (1507, 2, 1)
insert into MerchantSharedWebsitePages (merchantID, SharedWebsitePageId, AlwaysRecalculate)
values (1507, 3, 1)
insert into MerchantSharedWebsitePages (merchantID, SharedWebsitePageId, AlwaysRecalculate)
values (1507, 4, 1)
insert into MerchantSharedWebsitePages (merchantID, SharedWebsitePageId, AlwaysRecalculate)
values (1507, 5, 1)
insert into MerchantSharedWebsitePages (merchantID, SharedWebsitePageId, AlwaysRecalculate)
values (1507, 6, 1)
insert into MerchantSharedWebsitePages (merchantID, SharedWebsitePageId, AlwaysRecalculate)
values (1507, 7, 1)
insert into MerchantSharedWebsitePages (merchantID, SharedWebsitePageId, AlwaysRecalculate)
values (1507, 8, 1)
insert into MerchantSharedWebsitePages (merchantID, SharedWebsitePageId, AlwaysRecalculate)
values (1507, 9, 1)
insert into MerchantSharedWebsitePages (merchantID, SharedWebsitePageId, AlwaysRecalculate)
values (1507, 10, 1)
insert into MerchantSharedWebsitePages (merchantID, SharedWebsitePageId, AlwaysRecalculate)
values (1507, 11, 1)
insert into MerchantSharedWebsitePages (merchantID, SharedWebsitePageId, AlwaysRecalculate)
values (1507, 12, 1)
insert into MerchantSharedWebsitePages (merchantID, SharedWebsitePageId, AlwaysRecalculate)
values (1507, 13, 1)